[package]
name = "pikru-compare"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = { git = "https://github.com/facet-rs/facet", branch = "main" }
facet-svg = { git = "https://github.com/facet-rs/facet", branch = "main" }
facet-assert = { git = "https://github.com/facet-rs/facet", branch = "main" }
miette = { version = "7.6.0", features = ["fancy"] }
camino = "1.2.1"
